"""empty message

Revision ID: 6ab99957ee2a
Revises: 
Create Date: 2023-09-10 13:46:39.154360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab99957ee2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'staff', name='permissionlevels'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('leave_requets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_start', sa.DateTime(), nullable=False),
    sa.Column('leave_end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_paid_leave', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.Enum('holiday', 'time_off', 'sick_leave', 'maternity_leave', 'paternity_leave', 'training_day', name='leaverequesttype'), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=250), nullable=True),
    sa.Column('actioned_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_requets')
    op.drop_table('employees')
    op.drop_table('users')
    # ### end Alembic commands ###
